server:
    port: 8080
    
spring:
    main:
        banner-mode: OFF
        log-startup-info: false
    application:
        name: api-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            routes:
                - id: url-route
                  uri: lb://backend
                  predicates: 
                    - Path=/api/v1/urls/**
                - id: account-route
                  uri: lb://backend
                  predicates: 
                    - Path=/api/v1/account/**
                - id: url-feed-service
                  uri: lb://url-feed-service
                  predicates: 
                    - Path=/api/v1/feed/recent/**
    r2dbc:
        url: r2dbc:postgresql://db:5432/my_db
        username: admin
        password: admin
app:
    secretKey: verystrongsupersecurekey12345678 
    
eureka:
    client:
        service-url:
            defaultZone: http://eureka:8761/eureka/
        