server:
    port: 8080
    
spring:
    main:
        banner-mode: OFF
        log-startup-info: false
    application:
        name: api-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            routes:
                - id: url-route
                  uri: lb://backend
                  predicates: 
                    - Path=${BACKEND_URL_PATH}
                - id: account-route
                  uri: lb://backend
                  predicates: 
                    - Path=${BACKEND_ACC_PATH}
                - id: url-feed-service
                  uri: lb://url-feed-service
                  predicates: 
                    - Path=${FEED_PATH_URL}
    r2dbc:
        url: ${DB_URL}
        username: ${DB_USERNAME} 
        password: ${DB_PASSWORD}
app:
    secretKey: ${MY_SECRET_KEY} 
    api-key: ${MY_API_KEY}
    
management:
    endpoints:
        web:
            exposure:
                include: prometheus
    prometheus:
        metrics:
            export:
                enabled: true
    
eureka:
    client:
        service-url:
            defaultZone: ${SERVICE_DISCOVERY_URL}
        