server:
    port: 8099
spring:
  main:
    banner-mode: OFF
    log-startup-info: false
  application:
    name: url-feed-service
  data:
    redis:
        host: redis
        port: 6379
management:
    endpoints:
        web:
            exposure:
                include: prometheus
    prometheus:
        metrics:
            export:
                enabled: true
eureka:
    client:
        service-url:
            defaultZone: ${SERVICE_DISCOVERY_URL}
app:
    secretKey: ${MY_SECRET_KEY}
    api-key: ${MY_API_KEY}