global:
  scrape_interval: "1m"

scrape_configs:
  - job_name: 'url-shortener'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - api-gateway:8080
          - backend:8081
          - url-feed-service:8099