pipeline {
    agent any
    stages {
        stage('Checkout'){
            steps {
                git clone 'https://github.com/josephC45/url_shortner.git'
            }
        }
        stage('Build'){
            steps {
                sh 'mvn clean install'
            }
        }
        stage('Test'){
            steps {
                sh 'mvn test'
            }

            post {
                always {
                    // Archive the test results
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
    }

    post {
        always {
            // Clean up after the build
            cleanWs()
        }
    }
}