server:
    port:
        8761
spring:
    main:
        banner-mode: OFF
        log-startup-info: false
    application:
        name: service-discovery

eureka:
    client:
        fetchRegistry: false
        register-with-eureka: false
        service-url:
            defaultZone: ${SERVICE_DISCOVERY_URL}