server:
    port:
        8081
spring:
    main:
        banner-mode: OFF
        log-startup-info: false
    application:
        name: backend
    r2dbc:
        url: r2dbc:postgresql://db:5432/my_db
        username: admin
        password: admin
logging:
    level:
        io:
            r2dbc:
                postgresql:
                    QUERY: DEBUG
        org:
            springframework:
                r2dbc:
                    core: DEBUG
management:
    endpoints:
        web:
            exposure:
                include: prometheus
    prometheus:
        metrics:
            export:
                enabled: true
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
app:
    baseConversion: 62
    shortUrlBase: http://localhost:8081/