server:
    port: 8081
spring:
    main:
        banner-mode: OFF
        log-startup-info: false
    application:
        name: backend
    r2dbc:
        url: ${DB_URL} 
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
logging:
    level:
        io:
            r2dbc:
                postgresql:
                    QUERY: DEBUG
        org:
            springframework:
                r2dbc:
                    core: DEBUG
management:
    endpoints:
        web:
            exposure:
                include: prometheus
    prometheus:
        metrics:
            export:
                enabled: true
eureka:
    client:
        service-url:
            defaultZone: ${SERVICE_DISCOVERY_URL}
app:
    baseConversion: ${BASE_CONVERSION}
    shortUrlBase: ${BASE_SHORT_URL}
    secretKey: ${MY_SECRET_KEY}
    api-key: ${MY_API_KEY}