name: Run Tests for URL Shortener

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: windows-latest
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
  
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
  
      - name: Run Unit Tests
        run: mvn clean test -Dtest=com.SpringBootApp.UrlShortner.UnitTesting.*

      - name: Run Integration Tests
        run: mvn clean test -Dtest=com.SpringBootApp.UrlShortner.IntegrationTesting.*

      - name: Run E2E Tests
        run: mvn clean test -Dtest=com.SpringBootApp.UrlShortner.EndToEndTesting.*
        
