name: Run Tests for URL Shortener

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: windows-latest
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
  
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
  
      - name: Build and Run Tests (Maven)
        run: mvn clean test
